// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Techly.DAL.Context;

#nullable disable

namespace Techly.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250909195240_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Techly.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Mobile Accessories"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Power & Charging"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Headphones & Audio"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Smart Gadgets"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
